### ISSUE TITLE
Server version release to support OpenUPM

### ISSUE THREAD

**Issue by JohannesDeml** [ARM-software/mobile-studio-integration-for-unity#2]
I would love to see a proper [semver](https://semver.org/) version release such as 1.0.1. This would make it possilbe to use this package with [OpenUPM](https://openupm.com/packages/com.arm.mobile-studio/).

**Comment by danbai02** [comment]
I've renamed the 1.0 release in GitHub to 1.0.0 - and we will follow the semantic versioning with any future releases as well. Does this resolve this issue?

**Comment by JohannesDeml** [comment]
Awesome, thanks! yes that solves the compatibility problem with openupm.
